Update Dockerfile.migrate

diff --git a/Dockerfile.migrate b/Dockerfile.migrate
--- a/Dockerfile.migrate
+++ b/Dockerfile.migrate
@@ -17,20 +17,20 @@ COPY . .
 ENV NEXT_TELEMETRY_DISABLED=1
 
 # build Next + emit Drizzle SQL
-RUN \
-  if [ -f yarn.lock ];        then SKIP_ENV_VALIDATION=1 yarn build      && yarn dlx drizzle-kit generate; \
-  elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build && npx drizzle-kit generate; \
-  elif [ -f pnpm-lock.yaml ];    then npm install -g pnpm                && SKIP_ENV_VALIDATION=1 pnpm run build && pnpm dlx drizzle-kit generate; \
-  else echo "Lockfile not found." && exit 1; fi
+#RUN \
+  #if [ -f yarn.lock ];        then SKIP_ENV_VALIDATION=1 yarn build      && yarn dlx drizzle-kit generate; \
+ # elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build && npx drizzle-kit generate; \
+ # elif [ -f pnpm-lock.yaml ];    then npm install -g pnpm                && SKIP_ENV_VALIDATION=1 pnpm run build && pnpm dlx drizzle-kit generate; \
+ # else echo "Lockfile not found." && exit 1; fi
 
 FROM --platform=linux/amd64 node:20-alpine
 WORKDIR /app
 
 # copy only what the CLI needs
 COPY --from=deps    /app/node_modules      ./node_modules
-COPY --from=builder /app/migrations        ./migrations
-COPY                 drizzle.config.*      ./          # ts or js
-COPY package.json                           ./
+#COPY --from=builder /app/migrations        ./migrations
+#COPY                 drizzle.config.*      ./          # ts or js
+#COPY package.json                           ./
 
 #ENTRYPOINT ["npx","drizzle-kit","migrate","--yes"]
 ENTRYPOINT ["sh", "-c", "echo 'hello and goodbye test'"]
